#!/bin/bash
set -e

CC=aarch64-linux-gnu-gcc
LD=aarch64-linux-gnu-ld
CFLAGS="-ffreestanding -nostdlib -static -O2 -Wall -I user -Wno-unused-function"

echo "Building userspace for ARM64..."

APPS="init hello shell echo ls cat fuzz"

for APP in $APPS; do
    echo "Compiling $APP..."
    $CC $CFLAGS user/${APP}.c user/libc.c -o user_${APP}.elf
done

echo "Generating user_images_arm64.inc..."

echo "// Auto-generated by scripts/build_user_arm64.sh" > kernel/user_images_arm64.inc

for APP in $APPS; do
    echo "Converting $APP..."
    echo "const uint8_t user_image_${APP}[] = {" >> kernel/user_images_arm64.inc
    xxd -i < user_${APP}.elf >> kernel/user_images_arm64.inc
    echo "};" >> kernel/user_images_arm64.inc
    echo "const uint64_t user_image_${APP}_len = sizeof(user_image_${APP});" >> kernel/user_images_arm64.inc
done

echo "Done."
